# Generated by Django 5.2.17 on 2026-09-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default='', max_length=20),
        ),
    ]
